# Generated by Django 5.2.7 on 2026-03-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0043_alter_complementaryoffer_visit_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPendingVisitAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('scan', 'Scan'), ('pin', 'PIN')], max_length=16)),
                ('state', models.CharField(choices=[('started', 'Started'), ('awaiting_branch', 'Awaiting branch verification'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='started', max_length=32)),
                ('desk', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_visit_attempts', to='offers.branch')),
                ('qr_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_attempts', to='offers.qrtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_visit_attempts', to=settings.AUTH_USER_MODEL)),
                ('yashpin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_attempts', to='offers.yashpin')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
