# Generated by Django 5.2.7 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0044_userpendingvisitattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpendingvisitattempt',
            name='note',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
