# Generated by Django 5.2.7 on 2026-04-20 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0045_userpendingvisitattempt_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userofferclaim',
            name='uniq_user_branch_offer_milestone',
        ),
        migrations.AlterField(
            model_name='userofferclaim',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=12),
        ),
        migrations.AddIndex(
            model_name='userofferclaim',
            index=models.Index(fields=['user', 'branch', 'issued_at'], name='offers_user_user_id_e33055_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferclaim',
            index=models.Index(fields=['user', 'status', 'issued_at'], name='offers_user_user_id_8995f7_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferclaim',
            index=models.Index(fields=['branch', 'status', 'issued_at'], name='offers_user_branch__53cc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferclaim',
            index=models.Index(fields=['offer', 'issued_at'], name='offers_user_offer_i_df590f_idx'),
        ),
        migrations.AddIndex(
            model_name='userofferclaim',
            index=models.Index(fields=['milestone_kind', 'milestone_n'], name='offers_user_milesto_60d52a_idx'),
        ),
    ]
