# Generated by Django 5.2.7 on 2026-04-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0046_remove_userofferclaim_uniq_user_branch_offer_milestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservisitevent',
            name='visit_method',
            field=models.CharField(choices=[('qr_code', 'QR Code'), ('qr_pin', 'QR PIN Entry'), ('offer_day_pin', 'Offer Day PIN')], max_length=20),
        ),
    ]
