# Generated by Django 5.2.7 on 2026-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0047_alter_uservisitevent_visit_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstaff',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='branchstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
