# Generated by Django 5.2.7 on 2026-05-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0048_branchstaff_is_active_branchstaff_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStaffEmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=12)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_email_otps', to='offers.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'email', 'used'], name='offers_bran_branch__d1dc61_idx'), models.Index(fields=['branch', 'email', 'expires_at'], name='offers_bran_branch__d420c6_idx'), models.Index(fields=['created_at'], name='offers_bran_created_da6526_idx')],
            },
        ),
    ]
