# Generated by Django 5.2.7 on 2026-05-02 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0049_branchstaffemailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('deactivate', 'Deactivated'), ('reactivate', 'Reactivated')], max_length=20)),
                ('staff_name_snapshot', models.CharField(blank=True, max_length=80)),
                ('staff_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('staff_id_snapshot', models.CharField(blank=True, max_length=30)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_by_name', models.CharField(default='Branch owner', max_length=80)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.branch')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='offers.branchstaff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
