# Generated by Django 5.2.7 on 2026-05-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0050_branchstaffactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstaffactivitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('deactivate', 'Deactivated'), ('reactivate', 'Reactivated'), ('delete', 'Deleted')], max_length=20),
        ),
    ]
