# Generated by Django 5.2.7 on 2026-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0051_alter_branchstaffactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstaff',
            name='active_session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='branchstaff',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
