# Generated by Django 5.2.7 on 2026-05-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0052_branchstaff_active_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location_subtitle',
            field=models.CharField(blank=True, default='', help_text='Optional street / landmark details. Example: Ramalayam Street, 4th Phase', max_length=160),
        ),
        migrations.AddField(
            model_name='branch',
            name='location_title',
            field=models.CharField(blank=True, default='', help_text='Short area name shown on user branch card. Example: Kukatpally', max_length=80),
        ),
    ]
