# Generated by Django 5.2.7 on 2026-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0053_branch_location_subtitle_branch_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='display_title',
            field=models.CharField(blank=True, default='', help_text='User-facing branch title. Example: Prasad Family Restaurant', max_length=120),
        ),
    ]
