# Generated by Django 5.2.7 on 2026-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0054_branch_display_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementaryoffer',
            name='offer_image',
            field=models.ImageField(blank=True, null=True, upload_to='offer_images/'),
        ),
    ]
