# Generated by Django 5.2.7 on 2026-05-14 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0055_complementaryoffer_offer_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yashpin',
            name='pin_lookup',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='yashpin',
            index=models.Index(fields=['pin_lookup', 'used', 'expires_at'], name='offers_yash_pin_loo_03f76b_idx'),
        ),
    ]
